services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - mongodb
    env_file: ../.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  mongodb:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo_data:
